### ISSUE TITLE
Reconsider enabling parallel processing for `chromatograms` call

### ISSUE THREAD

**Issue by jorainer** [mjhelf/Metaboseek#121]
In `multiEIC` (https://github.com/mjhelf/METABOseek/blob/bb55f521c2d3aa5e804034213253c1466cdbd956/R/Functions_extract_EICs.R#L235) you disable parallel processing for `chromatograms`. For a single feature/ion this could make sense, but if you extract ion chromatograms for several features/ranges at once I would use parallel processing as it *should* be faster. One possible reason why it could be slower is if you use `SnowParam`. 

Some tips here:
1) use if possible `MulticoreParam`, as this will fork the process instead of starting a new R instance. `SnowParam` will thus have to start a new `R`, and load all required libraries before it can run the code in parallel. This takes quite some time and could be a reason that parallel processing might appear slower than serial processing.
2) Initialize the parallel processing setup at the start and don't manually specify them in individual function calls. I found it usefull to call e.g. `register(bpstart(MulticoreParam(2)))` or `register(bpstart(SnowParam(2)))` right at the start of the session. With the `bpstart` you explicitly initialyze the forks or sockets and every parallel processing call should start faster (could also help with socket-based parallel processing on windows - but did not try that).

In any rate, there is a *parallel processing* section in the xcms vignette that describes this a little.

**Comment by mjhelf** [comment]
Thank you for the suggestion, @jotsetung !

It will probly make sense to use parallel processing for this, especially when it is not used for the graphical output for a single feature (but even in that case, I'm thinking of making a cache of EICs in the background so that they can be instantly displayed when a user changes their selection in the main table - that is currently handled by the old xcmsRaw methods).

You are absolutely right that I should use `MulticoreParam` more often (across the code). However, most users of METABOseek are currently using Windows, so I would have to use `SnowParam` in many cases, and because that has so much overhead to get started, I sometimes only used multiple workers when the parallel jobs are relatively large. 

This may no longer be necessary, because:
Your suggestion to use register() may prove to be solid gold. It is a good idea to make a default setting globally to begin with, depending on the OS either `register(bpstart(MulticoreParam(2)))` or `register(bpstart(SnowParam(2)))`.

I tested this just to look at the overhead in Windows:
```
register(bpstart(SnowParam(2)))

microbenchmark(lapply = lapply(c(10:15), sqrt),
               serial = bplapply(c(10:15), sqrt, BPPARAM = SerialParam()),
               Multicore = suppressWarnings({bplapply(c(10:15), sqrt, BPPARAM = MulticoreParam(workers = 2))}),
               SnowParam_2w = bplapply(c(10:15), sqrt, BPPARAM = SnowParam(workers = 2)),
               SnowParam_registered_2w = bplapply(c(10:15), sqrt, BPPARAM = bpparam()),
               SnowParam_1w = bplapply(c(10:15), sqrt, BPPARAM = SnowParam(workers = 1)),               
               times = 5)

```

It looks like trying to use `MulticoreParam` under Windows lets it run with a performance hit compared to serial or registered `SnowParam`. The amazingly interesting thing for me though is that using register() is really doing away with most of the overhead of `SnowParam`. I'll start to implement this everywhere I can. Thank you!
```
Unit: microseconds
                    expr        min         lq        mean     median         uq        max neval
                  lapply     13.653     17.749     17.5446     18.091     18.774     19.456     5
                  serial   1589.249   1601.537   1672.3974   1632.598   1633.280   1905.323     5
               Multicore   3789.825   3917.142   4000.0864   3938.305   4177.239   4177.921     5
            SnowParam_2w 563069.707 566516.491 573232.8402 574038.797 576865.378 585673.828     5
 SnowParam_registered_2w   1698.134   1753.771   1792.4784   1811.457   1839.105   1859.925     5
            SnowParam_1w   4475.905   4514.135   4608.9570   4549.292   4649.303   4856.150     5
```

**Comment by jotsetung** [comment]
Nice to see that it helps on Windows. Actually - I have no idea what `MulticoreParam` does on Windows - I guess falling back to `SnowParam`.
